name: Package Application with PyInstaller for Linux
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
      - "b*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Package Application with PyInstaller
        run: |
          pyinstaller build.spec

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: dist

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Application
          prerelease: ${{ startsWith(github.ref_name, 'b') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
